export type Severity = 'CRITICAL' | 'MEDIUM' | 'MINOR' | 'UNQUALIFIED';

export type ResolutionState = 'OPEN' | 'ACKNOWLEDGED' | 'FIXED' | 'DEPLOYED' | 'VERIFIED_FIXED' | 'ARCHIVED' | 'REGRESSION' | 'IGNORED';

export interface ErrorLog {
    id: string;
    timestamp: string; // ISO string
    application: string; // e.g., "PaymentService", "AuthApp"
    level: 'ERROR' | 'WARN' | 'CRITICAL';
    message: string;
    env: 'prod' | 'stage' | 'dev'; // Added environment
    stackTrace?: string;
    metadata?: Record<string, unknown>;
}

export interface ErrorGroup {
    id: string;
    title: string; // generated by AI
    description: string;
    severity: 'UNQUALIFIED' | 'MINOR' | 'MEDIUM' | 'CRITICAL';
    category: 'APPLICATION' | 'INFRASTRUCTURE'; // New field
    appId: string; // Service identifier
    status: ResolutionState;
    env: 'prod' | 'stage' | 'dev'; // Added environment

    // Aggregated data
    firstSeen: string;
    lastSeen: string;
    occurrenceCount: number;

    // Linked logs
    logs: ErrorLog[];

    // Workflow Metadata
    assignee?: string; // specific dev or team
    acknowledgedAt?: string;
    fixedAt?: string;
    deployedAt?: string;
    deployedVersion?: string;

    // Timeline / History
    timeline: TimelineEvent[];

    // AI/Intelligence Metadata
    patternSignature: string; // internal signature for grouping
    runbookUrl?: string; // Auto-mapped documentation
    aiSummary?: string;
    aiSuggestedFix?: string;
    aiLocation?: string;

    // Regression / Versioning
    regressionOf?: string; // ID of the parent incident
    version?: number; // 1 = original, 2 = regression, etc.
}

export interface TimelineEvent {
    id: string;
    timestamp: string;
    actor: string;
    action: IncidentAction | 'creation';
    status: ResolutionState;
    comment?: string;
}

export interface StatusUpdatePayload {
    version?: string;
    assignee?: string;
    comment?: string;
}

export type IncidentAction = 'acknowledge' | 'fix' | 'deploy' | 'archive' | 'qualify' | 'verify' | 'simulate_regression' | 'ignore' | 'restore';

export interface ActionPayload {
    version?: string;
    severity?: ErrorGroup['severity'];
}

export interface AnalyticsDataPoint {
    date: string;
    errors: number;
    deployments: number;
    traffic: number; // Simulated usage/hits
}

export interface AppStats {
    appName: string;
    active: number;
    total: number; // Cumulative (including occurrences)
    regressions: number;
    healthScore: number;
    uniqueErrors: number;
    status: 'healthy' | 'warning' | 'critical';
    dailyStats: {
        date: string; // "Mon", "Tue" etc.
        count: number;
        regressions: number;
    }[];
}

export type SortStrategy = 'urgency' | 'volume' | 'recency' | 'debt';

export interface BackendIncident {
    id: string;
    errorHash: string;
    message: string;
    stackTrace: string; // string in DB, not optional
    serviceName: string;
    environment: string;
    severity: Severity;
    status: ResolutionState;
    occurrenceCount: number;
    firstSeen: string; // Date string
    lastSeen: string; // Date string
    metadata: Record<string, unknown>;
    aiSummary?: string;
    aiSuggestedFix?: string;
    aiLocation?: string;
}

export interface IngestPayload {
    message: string;
    serviceName: string;
    environment: string;
    stackTrace?: string;
    metadata?: Record<string, unknown>;
    timestamp?: string;
}
